"""Load and parse address profiles from profile/<name> files."""

from __future__ import annotations

from chaddr.profile.fetch import (
    ProfileAddressFetchEvent,
    iter_profile_address_fetch,
    list_profile_candidate_addresses,
)
from chaddr.profile.history import (
    AddrHistoryRecord,
    addr_history_records_to_sets,
    addr_history_to_sets,
    append_profile_addr_history,
    format_addr_history_timestamp,
    parse_addr_history_arg,
    parse_history_addr_args,
    write_profile_history,
)
from chaddr.profile.instance import (
    FROM_TYPE_SOURCE_LABELS,
    INSTANCE_FROM_HANDLERS,
    canonical_from_type_label,
    cloud_from_block_options,
    ec2_from_block_options,
    handler_config_for_instance_from,
    instance_from_block_addresses,
    instance_profile_addresses,
    is_instance_from_type,
    resolve_profile_addresses,
)
from chaddr.profile.instructions import list_profile_instructions
from chaddr.profile.model import (
    Profile,
    ProfileEntry,
    ProfileFromBlock,
    ProfileHeader,
    ProfileInstruction,
    profile_option_truthy,
)
from chaddr.profile.parse import (
    PATH_TYPE_SHORTHANDS,
    STARTER_FROM,
    STARTER_TYPE,
    format_profile_label,
    list_profile_items,
    list_profiles,
    load_profile,
    merge_cli_options,
    profile_from_blocks,
    update_profile_entry_option,
)
from chaddr.profile.paths import (
    PKGDATADIR,
    PROFILE_DIR,
    USER_PROFILE_DIR,
    display_profile_path,
    ensure_profile_dir,
    format_profile_dir_label,
    get_profile_dir,
    set_profile_dir,
)

__all__ = [
    "PKGDATADIR",
    "PROFILE_DIR",
    "USER_PROFILE_DIR",
    "STARTER_FROM",
    "STARTER_TYPE",
    "PATH_TYPE_SHORTHANDS",
    "INSTANCE_FROM_HANDLERS",
    "FROM_TYPE_SOURCE_LABELS",
    "AddrHistoryRecord",
    "ProfileHeader",
    "ProfileEntry",
    "ProfileFromBlock",
    "ProfileInstruction",
    "Profile",
    "ProfileAddressFetchEvent",
    "display_profile_path",
    "format_profile_dir_label",
    "get_profile_dir",
    "ensure_profile_dir",
    "set_profile_dir",
    "format_addr_history_timestamp",
    "parse_history_addr_args",
    "parse_addr_history_arg",
    "addr_history_to_sets",
    "addr_history_records_to_sets",
    "write_profile_history",
    "append_profile_addr_history",
    "profile_option_truthy",
    "list_profiles",
    "format_profile_label",
    "list_profile_items",
    "load_profile",
    "merge_cli_options",
    "update_profile_entry_option",
    "is_instance_from_type",
    "canonical_from_type_label",
    "cloud_from_block_options",
    "ec2_from_block_options",
    "handler_config_for_instance_from",
    "instance_from_block_addresses",
    "instance_profile_addresses",
    "resolve_profile_addresses",
    "profile_from_blocks",
    "list_profile_instructions",
    "iter_profile_address_fetch",
    "list_profile_candidate_addresses",
]
